#!/bin/sh
#update remote ref with current branch in commit message: helps ensure project pattern
commitMessage=$1
currentBranch=$(git symbolic-ref --short -q HEAD) 
export og=$(git remote)
if [ ! -z "$1" ]; then
	if [ "$currentBranch" == "main" ]; then
		echo "\x1b[31mpushing to main branch is blocked. \n> are you trying to checkout : $commitMessage \x1b[0m \n"
	else
		git add .
		git commit -m "$currentBranch: $1"
		git push $og $currentBranch
		echo "\x1b[32mpushed: $currentBranch to $og as '$1' \x1b[0m \n"
	fi
else
	echo "\x1b[34mplease provide a commit message. \n> git abc 'your commit message' \x1b[0m \n"
fi