#!/bin/sh
#update remote ref with current branch in commit message: helps project board linking
commitMessage=$1
currentBranch=$(git symbolic-ref --short -q HEAD) 
export og=$(git remote)
if [ ! -z "$1" ]
then
git add .
git commit -m "$currentBranch: $1"
git push $og $currentBranch
echo "\x1b[32mPushed: $currentBranch to $og as '$1' \x1b[0m \n"
else
echo "\x1b[34mPlease provide a commit message. \n> git abc 'your commit message' \x1b[0m \n"
fi