#!/bin/sh
#update fetch and rebase current branch with remote head
currentBranch=$(git symbolic-ref --short -q HEAD) 
export og=$(git remote)

git fetch
git pull $og $currentBranch
echo "\x1b[32mpulled: latest $currentBranch from $og \x1b[0m \n"

